services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/custom.conf:ro
    networks:
      - app_network
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx_letsencrypt
    depends_on:
      - nginx-proxy
    environment:
      NGINX_PROXY_CONTAINER: nginx_proxy
      DEFAULT_EMAIL: tu_correo@ejemplo.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - app_network
    restart: always

  postgres:
    image: postgres:13-alpine
    container_name: gosport_db
    environment:
      POSTGRES_USER: gosport_user
      POSTGRES_PASSWORD: gosport_password
      POSTGRES_DB: gosport_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./DataBase/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./DataBase/dml.sql:/docker-entrypoint-initdb.d/02-dml.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gosport_user -d gosport_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network
    restart: unless-stopped

  api:
    build: ./api/
    container_name: gosport_api
    environment:
      DB_NAME: gosport_db
      DB_USER: gosport_user
      DB_PORT: 5432
      DB_HOST: postgres
      DB_PASSWORD: gosport_password
      PORT: 8080
      VIRTUAL_HOST: api.tudominio.com
      LETSENCRYPT_HOST: api.tudominio.com
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    expose:
      - "8080"
    restart: unless-stopped

  client:
    build: ./client/
    container_name: gosport_client
    environment:
      VIRTUAL_HOST: tudominio.com
      LETSENCRYPT_HOST: tudominio.com
    networks:
      - app_network
    expose:
      - "80"
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
