CREATE TABLE "Usuario" (
  "cedula" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "nombre" VARCHAR(100) NOT NULL,
  "apellido" VARCHAR(100) NOT NULL,
  "correoElectronico" VARCHAR(255) NOT NULL UNIQUE,
  "telefono" VARCHAR(20) NOT NULL,
  "user_name" VARCHAR(50) NOT NULL UNIQUE,
  "contrasena" VARCHAR(255) NOT NULL
);

CREATE TABLE "Deporte" (
  "id_deporte" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "nombre" VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE "Cancha" (
  "id_cancha" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "nombre" VARCHAR(100) NOT NULL,
  "capacidad" INTEGER NOT NULL,
  "id_deporte" INTEGER NOT NULL,
  CONSTRAINT unique_cancha_deporte UNIQUE ("nombre", "id_deporte")
);

CREATE TABLE "Evento" (
  "id_evento" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "nombre" VARCHAR(100) NOT NULL,
  "fecha" DATE NOT NULL,
  "hora_inicio" TIME NOT NULL,
  "id_cancha" INTEGER NOT NULL
);

CREATE TABLE "Reserva" (
  "id_reserva" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "fecha" DATE NOT NULL,
  "hora_inicio" TIME NOT NULL,
  "hora_fin" TIME NOT NULL,
  "id_usuario" INTEGER NOT NULL,
  "id_cancha" INTEGER NOT NULL,
  CONSTRAINT unique_reserva_cancha_hora UNIQUE ("id_cancha", "fecha", "hora_inicio")
);

CREATE TABLE "Participante" (
  "id_participante" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "id_usuario" INTEGER NOT NULL,
  "id_evento" INTEGER NOT NULL,
  CONSTRAINT unique_participacion UNIQUE ("id_usuario", "id_evento")
);

-- Relaciones con comportamientos de eliminación definidos
ALTER TABLE "Cancha" ADD FOREIGN KEY ("id_deporte") REFERENCES "Deporte" ("id_deporte") ON DELETE CASCADE;

ALTER TABLE "Evento" ADD FOREIGN KEY ("id_cancha") REFERENCES "Cancha" ("id_cancha") ON DELETE CASCADE;

ALTER TABLE "Reserva" ADD FOREIGN KEY ("id_usuario") REFERENCES "Usuario" ("cedula") ON DELETE CASCADE;
ALTER TABLE "Reserva" ADD FOREIGN KEY ("id_cancha") REFERENCES "Cancha" ("id_cancha") ON DELETE CASCADE;

ALTER TABLE "Participante" ADD FOREIGN KEY ("id_usuario") REFERENCES "Usuario" ("cedula") ON DELETE CASCADE;
ALTER TABLE "Participante" ADD FOREIGN KEY ("id_evento") REFERENCES "Evento" ("id_evento") ON DELETE CASCADE;
