@startuml
skinparam packageStyle rectangle
skinparam actorStyle awesome

left to right direction

actor Usuario as U #palegreen
actor Administrador as A
rectangle "Sistema de Reservas Deportivas" {

  package "Autenticación" {
    usecase "Registrarse" as UC1 #palegreen;text:black
    usecase "Iniciar sesión" as UC2 #palegreen;text:black
    U --> UC1
    U --> UC2
  }

  package "Consultas" {
    usecase "Ver deportes disponibles" as UC3 #FFFF99;text:black
    usecase "Ver canchas disponibles" as UC4 #FFFF99;text:black
    usecase "Ver eventos" as UC5 #FFFF99;text:black
    usecase "Ver participantes de evento" as UC6 #FFFF99;text:black
    usecase "Ver reservas" as UC7 #FFFF99;text:black
    U --> UC3
    U --> UC4
    U --> UC5
    U --> UC6
    A --> UC7
  }

  package "Reservas" {
    usecase "Reservar cancha" as UC8 #FFFF99;text:black
    usecase "Consultar disponibilidad de cancha" as UC9 #FFFF99;text:black
    usecase "Cancelar reserva" as UC10 #FFFF99;text:black
    U --> UC8
    UC8 --> UC9 : <<include>>
    U --> UC10
    UC10 --> UC8 : <<extend>>
  }

  package "Eventos" {
    usecase "Unirse a evento" as UC11 #FFFF99;text:black
    usecase "Ver eventos" as UC12 #FFFF99;text:black
    usecase "Cancelar participación en evento" as UC13 #FFFF99;text:black
    usecase "Crear evento" as UC14 #FFFF99;text:black
    U --> UC11
    UC11 --> UC12 : <<include>>
    U --> UC13
    UC13 --> UC11 : <<extend>>
    A --> UC14
    UC14 --> UC12 : <<include>>
    UC14 --> UC3 : <<include>>
  }

  package "Administración de Deportes" {
    usecase "Gestionar deportes" as UC15 #FFFF99;text:black
    usecase "Crear deporte" as UC16 #FFFF99;text:black
    usecase "Editar deporte" as UC17 #FFFF99;text:black
    usecase "Eliminar deporte" as UC18 #FFFF99;text:black
    A --> UC15
    UC15 --> UC16 : <<include>>
    UC15 --> UC17 : <<include>>
    UC15 --> UC18 : <<include>>
  }
}
@enduml
